name: msfno
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python==3.11.7
  # xarray
  - xarray
  - dask
  - bottleneck
  - cfgrib
  - hdf5
  - packaging
  - pandas
  - scipy
  - zarr
  - netcdf4
  - cftime
  # acceleration
  - numba
  - numbagg
  - flox
  - xskillscore

  # pytorch
  - pytorch-cuda=11.8
  - pytorch
  - timm
  - torchdata               
  - pyg
  
  # general utility
  - einops
  - git
  - gitpython
  - pip
  - python-dateutil
  - setuptools
  - six
  - tqdm
  - wheel
  - ruamel.yaml
  - yaml
  - gputil
  - matplotlib
  - cartopy
  - nc-time-axis
  - seaborn
  - jupyter
  - jupyter_server>=2.0.0
  - code-server
  - ipython
  - memory_profiler
  - wandb
  - rechunker                 # only used if you need to rechunk your data
  - gsutil                    # used if you download weatherbench from google storage

  - pip:
      - torch-harmonics
      - nvsmi                 # to print provenance and gpu information 
      - ecmwflibs             
      - climetlab             # used to handle grib files
