name: model
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # xarray
  - dask
  - bottleneck
  - cfgrib
  - hdf5
  - packaging
  - pandas
  - scipy
  # acceleration
  - numba
  - numbagg
  - flox

  # pytorch
  - pytorch-cuda=11.8
  - pytorch
  - timm
  - torchdata               # (atomdata)

  # ai-models
  - ruamel.yaml
  
  # general utility
  - einops
  - git
  - gitpython
  - pip
  - python-dateutil
  - setuptools
  - six
  - tqdm
  - wheel
  - yaml
  - gputil
  - matplotlib
  - cartopy
  - nc-time-axis
  - seaborn
  - jupyter
  - jupyter_server>=2.0.0
  - memory_profiler

  - pip:
      - atmodata
      - torch-harmonics
      - nvsmi                 # (ai-models, provenance, gpu) 
      - ecmwflibs             # (ai-models)
      - climetlab             # (ai-models)

# may needed trition