name: model
channels:
  - conda-forge
  - defaults
dependencies:

  # - pip: 
  #     #
  #     - apache-beam

  - python ==3.11.7
  - xarray
  - dask
  - rechunker 
  - immutabledict
  - apache-beam
  - apache-beam-with-dask
  - xarray-beam
  - bottleneck
  - cfgrib
  - pandas
  - scipy
  - zarr
  - netcdf4
  - cftime
  # acceleration
  - numbagg
  - flox

  # general
  - git
  - gitpython
  - pip
  - python-dateutil
  - setuptools
  - yaml
  - matplotlib
  - cartopy
  - jupyter
  - jupyter_server>=2.0.0
  - xskillscore

      

# may needed trition